#!/bin/sh

set -e

mark_xxx() {
  for f in ${1}
  do
    echo "${BASE_IMAGE}: ${f} is ${2}: ${3}" >&2
    FILT_ADD="${f} ${FILT_ADD}"
  done
}

mark_broken() {
  mark_xxx "${1}" "BROKEN" "${2}"
}

mark_disabled() {
  mark_xxx "${1}" "DISABLED" "${2}"
}

fltplatforms() {
  mark_disabled "linux/386 linux/arm/v5 linux/arm/v7" "Emulating 64-bit platforms on 32-bit hosts are discontinued in 10.x: https://gitlab.com/qemu-project/qemu/-/issues/3181"
  mark_broken "linux/riscv64 linux/s390x linux/mips64le" "host is not supported yet (send PR!)"
  if [ "${BASE_IMAGE%-*}" = "debian:13" ]
  then
    mark_broken "linux/ppc64le" "broken llvm port"
  fi
  FILT="grep -v -e unknown" # docker multi-arch is weird
  if [ ! -z "${FILT_ADD}" ]
  then
    for f in ${FILT_ADD}
    do
      FILT="${FILT} -e ^${f}\$"
    done
  fi
  ${FILT}
}

platformopts() {
  case "${BASE_IMAGE}" in
  debian:12*)
    EXTRA_CFLAGS="-DHAVE_BSD_STRING_H=1"
    case "${TARGETPLATFORM}" in
    linux/386|linux/arm/v5)
      EXTRA_CFLAGS="${EXTRA_CFLAGS} -Wno-atomic-alignment"
      ;;
    esac
    echo "export EXTRA_CFLAGS=\"${EXTRA_CFLAGS}\""
    echo "export EXTRA_LDFLAGS=\"-lbsd -lmd\""
    ;;
  esac
  test ! -z "${@}" && echo "${@}"
}

cmakeopts() {
  case "${BASE_IMAGE}" in
  debian:*)
    case "${TARGETPLATFORM}" in
    linux/arm/v5)
      echo "-DLIBATOMIC_STATIC_PATH=/usr/lib/gcc/arm-linux-gnueabi/12"
      ;;
    esac
    ;;
  esac
  test ! -z "${@}" && echo "${@}"
}

case "${1}" in
platformopts)
  shift
  platformopts "${@}"
  ;;
cmakeopts)
  shift
  cmakeopts "${@}"
  ;;
fltplatforms)
  fltplatforms
  ;;
*)
  echo "usage: `basename "${0}"` (platformopts|fltplatforms) [opts]" 2>&1
  exit 1
  ;;
esac
