#pragma once

#define TARGET_CLOCK_REALTIME		0
#define TARGET_CLOCK_VIRTUAL		1
#define TARGET_CLOCK_PROF		2
#define TARGET_CLOCK_MONOTONIC		4
#define TARGET_CLOCK_UPTIME_FAST	8
#define TARGET_CLOCK_UPTIME		5
#define TARGET_CLOCK_UPTIME_PRECISE	7
#define TARGET_CLOCK_REALTIME_PRECISE	9
#define TARGET_CLOCK_REALTIME_FAST	10
#define TARGET_CLOCK_MONOTONIC_PRECISE	11
#define TARGET_CLOCK_MONOTONIC_FAST	12
#define TARGET_CLOCK_SECOND		13
#define TARGET_CLOCK_THREAD_CPUTIME_ID	14
#define	TARGET_CLOCK_PROCESS_CPUTIME_ID 15
#define	TARGET_CLOCK_BOOTTIME		CLOCK_UPTIME
#define	TARGET_CLOCK_REALTIME_COARSE	CLOCK_REALTIME_FAST
#define	TARGET_CLOCK_MONOTONIC_COARSE	CLOCK_MONOTONIC_FAST

#define TARGET_TIMER_RELTIME	0x0	/* relative timer */
#define TARGET_TIMER_ABSTIME	0x1	/* absolute timer */

#define	TARGET_UMTX_ABSTIME		0x01
